---
 - name: play 1
   hosts: "*"
   become: yes
   tasks:
     - name: run command with shell
       shell: echo "hello, shell!" > /tmp/shell_output

     - name: run command with command
       command: echo "hello, command!" > /tmp/command_output
       