---

- name: run task on node
  hosts: node
  vars:
    env: staging
  tasks:
    - name: template file onto remote hosts
      template:
        src: my_app.conf.j2
        dest: /etc/my_app.conf
      become: true