---

- name: run task on node
  hosts: node
  vars:
    users:
     - name: vini
       username: vinay
     - name: siddharth
       username: sidd
  tasks:
    - name: ensure users exits
      user:
        name: "{{ user.username }}"
        comment: "{{ user.name }}"
        state: present
      become: true
      loop: "{{ users }}"
      loop_control:
        loop_var: user
