---

- name: run task on node
  hosts: node
  tasks:
   - name: copy file to remote host
     copy: 
       src: my_app.conf
       dest: /etc/my_app.conf
       owner: root
       group: root
       mode: 0600
     become: true