---
 - name: play 1
   hosts: "*"
   become: yes
   tasks:
     - name: use args, environment and loop with shell
       shell: echo "amazing, world!" > $TARGET
       args: 
         chdir: /tmp
       environment:
         TARGET: "{{ item }}"
       loop
         - test_file1
         - test_file5
