---
 - name: play 1
   hosts: webserver
   become: yes
   tasks:
     - name: execute command 'date'
       command: date

     - name: install httpd service
       yum:
          name: httpd
          state: present
     - name: start web server
       service:
          name: httpd
          state: started